# Generated by Django 6.0.6 on 2026-07-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_lesson_lessoninfo_delete_lessontable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='teacher',
            new_name='teacher_id',
        ),
        migrations.RenameField(
            model_name='lessoninfo',
            old_name='lesson',
            new_name='lesson_id',
        ),
    ]
