# Generated by Django 6.0.6 on 2026-07-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_rename_teacher_certificate_teacher_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='monthly_payment_base',
            field=models.IntegerField(null=True),
        ),
    ]
