# Generated by Django 6.0.6 on 2026-07-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_course_monthly_payment_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='aksiya',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
