# Generated by Django 6.0.6 on 2026-07-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_aksiya_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethods',
            old_name='bank_name',
            new_name='name',
        ),
    ]
