# Generated by Django 6.0.6 on 2026-07-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_rename_bank_name_paymentmethods_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='name',
            field=models.CharField(help_text='Bank or others', max_length=200),
        ),
    ]
