# Generated by Django 6.0.6 on 2026-07-26 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_alter_paymentmethods_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.course'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
