# Generated by Django 6.0.6 on 2026-07-26 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_rename_full_name_teacher_name_teacher_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='end_time',
        ),
    ]
