# Generated by Django 6.0.6 on 2026-07-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_events_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='start_time',
        ),
    ]
