# Generated by Django 6.0.6 on 2026-07-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_events_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='title',
            new_name='name',
        ),
    ]
