# Generated by Django 6.0.6 on 2026-07-27 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_rename_title_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='management.question'),
        ),
    ]
