# Generated by Django 6.0.6 on 2026-07-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_botuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
    ]
