# Generated by Django 6.0.6 on 2026-07-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_botuser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='chat_id',
            field=models.IntegerField(null=True),
        ),
    ]
