# Generated by Django 6.0.6 on 2026-07-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_registeruser_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='chat_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
