# Generated by Django 6.0.6 on 2026-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_botuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='chat_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
