from .start import *
from .help import *
from .register import *
from .course import *
from .lesson import *
from .prices_and_news import *
from .teacher import *
from .news import *
from .test import *